### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by dvc94ch** [pjotrp/guix#2]
Last commit was last year. I'm an active nix/nixos user and contemplating migrating/testing guix.

**Comment by pjotrp** [comment]
I also came from Nix. Guix is part of our deployment, see http://joss.theoj.org/papers/84b27b28948be80a47268a5baa2701ad

The official Guix repo is at https://savannah.gnu.org/git/?group=guix. See also my guix-notes at https://github.com/pjotrp/guix-notes

**Comment by dvc94ch** [comment]
Thanks!
